name: Build npm release

resources:
  - repo: self

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04

    steps:
      - task: NodeTool@0
        displayName: "Use Node 8.x"
        inputs:
          versionSpec: 8.x

      - script: "npm install -g esy@0.2.11 --unsafe-perm"
        displayName: "install esy"

      - script: "esy install"
        displayName: "esy install"

      - script: "esy build"
        displayName: "esy build"

      - script: "esy release"
        displayName: "esy release"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Linux"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: Linux

  - job: macOS
    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - task: NodeTool@0
        displayName: "Use Node 8.x"
        inputs:
          versionSpec: 8.x

      - script: "npm install -g esy@0.2.11 --unsafe-perm"
        displayName: "install esy"

      - script: "esy install"
        displayName: "esy install"

      - script: "esy build"
        displayName: "esy build"

      - script: "esy release"
        displayName: "esy release"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: macOS"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: macOS

  - job: Windows
    timeoutInMinutes: 120
    pool:
      vmImage: vs2017-win2016
      demands: npm

    steps:
      - task: NodeTool@0
        displayName: "Use Node 8.x"
        inputs:
          versionSpec: 8.x

      - script: "npm install -g esy@0.2.11 --unsafe-perm"
        displayName: "install esy"

      - script: "esy install"
        displayName: "esy install"
        continueOnError: true

      - script: "esy install"
        displayName: "esy install"
        continueOnError: true

      - script: "esy install"
        displayName: "esy install"
        continueOnError: true

      - script: "esy install"
        displayName: "esy install"

      - script: "esy build"
        displayName: "esy build"

      - script: "esy release"
        displayName: "esy release"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Windows"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: Windows

  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
    #      - Windows

    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - task: NodeTool@0
        displayName: "Use Node 8.x"
        inputs:
          versionSpec: 8.x

      - task: DownloadBuildArtifacts@0
        displayName: "Download Linux Artifacts"
        inputs:
          artifactName: Linux
          downloadPath: "_release"

      - script: "mkdir _release/platform-linux"
        displayName: "Create _release/platform-linux"

      - script: "cp -r _release/Linux/ _release/platform-linux"
        displayName: "cp Linux"

      - task: DownloadBuildArtifacts@0
        displayName: "Download macOS Artifacts"
        inputs:
          artifactName: macOS
          downloadPath: "_release"

      - script: "mkdir _release/platform-darwin"
        displayName: "Create _release/platform-darwin"

      - script: "cp -r _release/macOS/ _release/platform-darwin"
        displayName: "cp macOS"

      # - task: DownloadBuildArtifacts@0
      #   displayName: "Download Windows Artifacts"
      #   inputs:
      #     artifactName: Windows
      #     downloadPath: "_release"
      #   continueOnError: true

      # - script: "mkdir _release/platform-windows-x64"
      #   displayName: "Create _release/platform-windows-x64"
      #   continueOnError: true

      # - script: "cp -r _release/Windows/ _release/platform-windows-x64"
      #   displayName: "cp Windows"
      #   continueOnError: true

      - script: "node .ci/pipelines-release.js"
        displayName: "node .ci/pipelines-release.js"
        continueOnError: true

      - script: "npm pack"
        displayName: "npm pack"
        workingDirectory: "_release"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release"
        inputs:
          PathtoPublish: "_release/hello-reason-0.1.0.tgz"
          ArtifactName: Release

  - job: TestInstallLinux
    displayName: Test install Linux
    dependsOn:
      - Release

    pool:
      vmImage: ubuntu-16.04

    steps:
      - checkout: none

      - task: DownloadBuildArtifacts@0
        displayName: "Download release"
        inputs:
          artifactName: Release
          downloadPath: "release"

      - script: "npm i -g ./hello-reason-0.1.0.tgz"
        displayName: "install release"
        workingDirectory: "release/Release"

      - script: "hello-reason"
        displayName: "Test binary"

  - job: TestInstallmacOS
    displayName: Test install macOS
    dependsOn:
      - Release

    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - checkout: none

      - task: DownloadBuildArtifacts@0
        displayName: "Download release"
        inputs:
          artifactName: Release
          downloadPath: "release"

      - script: "npm i -g ./hello-reason-0.1.0.tgz"
        displayName: "install release"
        workingDirectory: "release/Release"

      - script: "hello-reason"
        displayName: "Test binary"

  - job: TestInstallWindows
    displayName: Test install Windows
    dependsOn:
      - Release

    pool:
      vmImage: vs2017-win2016
      demands: npm

    steps:
      - checkout: none

      - task: DownloadBuildArtifacts@0
        displayName: "Download release"
        inputs:
          artifactName: Release
          downloadPath: "release"

      - script: "npm i -g ./hello-reason-0.1.0.tgz"
        displayName: "install release"
        workingDirectory: "release/Release"

      - script: "hello-reason"
        displayName: "Test binary"
