name: Build npm release

resources:
  - repo: self

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04

    steps:
      - template: build-platform.yml

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Linux"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: Linux

  - job: macOS
    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - template: build-platform.yml

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: macOS"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: macOS

  - job: Windows
    timeoutInMinutes: 120
    pool:
      vmImage: vs2017-win2016
      demands: npm

    steps:
      - template: build-platform.yml

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Windows"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: Windows

  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows

    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - template: package-release.yml

  - job: TestInstallLinux
    displayName: Test install Linux
    dependsOn:
      - Release

    pool:
      vmImage: ubuntu-16.04

    steps:
      - script: |
          "mkdir ~/.npm-global"
          "npm config set prefix '~/.npm-global'"
          "export PATH=~/.npm-global/bin:$PATH"
          "source ~/.profile"
        displayName: "Workaround for global installs on Linux"

      - template: test-release.yml

  - job: TestInstallmacOS
    displayName: Test install macOS
    dependsOn:
      - Release

    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - template: test-release.yml

  - job: TestInstallWindows
    displayName: Test install Windows
    dependsOn:
      - Release

    pool:
      vmImage: vs2017-win2016
      demands: npm

    steps:
      - template: test-release.yml
